### ISSUE TITLE
traduction fr sur erreur d'écriture de repertoire

### ISSUE THREAD

**Issue by YGomiero** [infograf768/fr-FR-3.x#27]
#### Etat ####
- Serveur nginx, 
- répertoire protégé en écriture 
- tentative d'installation mise à jour pack de langue french 3.4.1.2
- génère des messages d'erreurs non traduit.

#### Capture d'écran ####
http://prntscr.com/6yenn0

* Message non traduit : 
JFolder::create
Unable to create destination

Manque string dans joomla : 
\libraries\joomla\archive\zip.php
ligne 304 :	`return JError::raiseWarning(100, 'Unable to create destination');`

* Pas de string "COM_INSTALLER_TYPE_TYPE_" pour l'alerte car le type n'est pas défini alors qu'il s'agit de la mise à jour du pack de langue.

**Comment by infograf768** [comment]
Yann, je te suggère de poster ceci en tant que bogue sur issues.joomla.org

**Comment by mahagr** [comment]
administrator/components/com_installer/models/update.php is missing check:

```		// Was the package unpacked?
		if (!$package || !$package['type'])
		{
			if (in_array($installType, array('upload', 'url')))
			{
				JInstallerHelper::cleanupInstall($package['packagefile'], $package['extractdir']);
			}

			$app->enqueueMessage(JText::_('COM_INSTALLER_UNABLE_TO_FIND_INSTALL_PACKAGE'), 'error');

			return false;
		}
```

Which is found in install.php lines 140-150.
