### ISSUE TITLE
New Joomla3.7.2 installation failed when selecting 'Brochure'

### ISSUE THREAD

**Issue by jbreeding** [infograf768/fr-FR-3.x#52]
Hi jm, details of this issue here.
https://github.com/joomla/joomla-cms/issues/16245

**Comment by infograf768** [comment]
I have replied in the Issue.
We will keep in this repository the specific french sample datas  (and strings) for the custom distrib.
Will now update these files in core to avoid confusion.

**Comment by Opware2000** [comment]
Thank you for your report.
I will see the origin of the error and propose a new version of the French pack. Probably tomorrow or Saturday.

**Comment by Opware2000** [comment]
#53
