### ISSUE TITLE
[com_installer] erreur sur la variable COM_INSTALLER_MSG_WARNINGS_UPDATE_NOTICE

### ISSUE THREAD

**Issue by Kedaos** [infograf768/fr-FR-3.x#62]
Hello !

Une erreur s'est glissée à la ligne 185 du fichier de traduction com_installer.
En effet, est indiqué `</ strong>` au lieu de `</strong>`

Du coup, lors de l'affichage du message, toute la page est en gras.

Testé avec la version 3.9.3.1

**Comment by infograf768** [comment]
Cela sera corrigé dans la prochaine version de Joomla. Merci.
