### ISSUE TITLE
traduction fr JTOOLBAR_DELETE_ALL

### ISSUE THREAD

**Issue by agerix** [infograf768/fr-FR-3.x#66]
Salut,

Serait possible de modifier dans le fichier administrator/language/fr-FR/fr-FR.ini, ligne 958 et passer de 
JTOOLBAR_DELETE="Supprimer"
JTOOLBAR_DELETE_ALL="Tout effacer"
à
JTOOLBAR_DELETE="Supprimer"
JTOOLBAR_DELETE_ALL="Tout supprimer"

Cela serait plus cohérent vis à vis des chaînes en anglais qui sont
JTOOLBAR_DELETE="Delete"
JTOOLBAR_DELETE_ALL="Delete All"

Merci !

**Comment by infograf768** [comment]
J'avais pas vu.
Ce sera fait pour 3.9.7 stable

**Comment by agerix** [comment]
Merci Jean-Marie
